<?php
    if (isset($articles) && is_array($articles) && ! empty($articles)) {
        ?>
        <section>
            <h2>Products</h2>
            <?php
            echo $view->renderWidget([
                'widget' => \Frontend\Widget\ListingArticles::class,
                'method' => 'renderWidget',
                'params' => [
                    'posts' => $articles
                ],
            ]);
            ?>
        </section>
        <?php
    }
?>

<?php
if (isset($textArticles) && is_array($textArticles) && ! empty($textArticles)) {
    ?>
    <section>
        <h2>Pinned Articles</h2>

        <?php
        echo $view->renderWidget([
            'widget' => \Frontend\Widget\ListingArticles::class,
            'method' => 'renderWidget',
            'params' => [
                'posts' => $textArticles
            ],
        ]);
        ?>

    </section>
    <?php
}
?>


<?php
if (isset($videoArticles) && is_array($videoArticles) && ! empty($videoArticles)) {
    ?>
    <section>
        <h2>Latest video articles</h2>

        <?php
        echo $view->renderWidget([
            'widget' => \Frontend\Widget\ListingArticles::class,
            'method' => 'renderWidget',
            'params' => [
                'posts' => $videoArticles
            ],
        ]);
        ?>
    </section>
    <?php
}
?>


