<?php

if (! isset($posts)) {
    return 'Post data missing!';
}

if (! isset($posts->content->rendered)) {
    echo 'Post content missing!';
    return;
}

echo $view->renderWidget([
    'widget' => \Frontend\Widget\Breadcrumbs::class,
    'method' => 'getPostBreadcrumbs',
    'params' => [
        'post' => $posts
    ],
]);

if (isset($featured_image)) {

    if (isset($featured_image->media_details->sizes->large->source_url)) {
        $img = $featured_image->media_details->sizes->large->source_url;
    } else {
        $img = $featured_image->media_details->sizes->full->source_url;
    }

    ?>
    <section class="container">
        <img src="<?php echo $img; ?>">
    </section>
    <?php
}

?>

<section class="container">
<?php echo $posts->content->rendered; ?>
</section>
