<?php

if (! isset($posts)) {
    return 'Post data missing!';
}

if (! isset($posts->content->rendered)) {
    echo 'Post content missing!';
    return;
}

echo $view->renderWidget([
    'widget' => \Frontend\Widget\Breadcrumbs::class,
    'method' => 'getPostBreadcrumbs',
    'params' => [
        'post' => $posts
    ],
]);

if (isset($featured_image)) {

    $featured_image = $featured_image[0];
    ?>
    <section class="container">
        <img src="<?php echo $featured_image->source_url    ; ?>">
    </section>
    <?php
}

?>

<section class="container">
    <?php echo $posts->content->rendered; ?>
</section>
