<?php

if (! isset($breadcrumbs) || ! is_array($breadcrumbs)) {
    echo 'Param breadcrumbs missing!';
    return;
}

?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <?php
        foreach ($breadcrumbs as $breadcrumb) {
            ?>
            <li class="breadcrumb-item"><a href="<?php echo $breadcrumb['link']; ?>"><?php echo $breadcrumb['name']; ?></a></li>
            <?php
        }
        ?>
    </ol>
</nav>