<?php

use Pagination\Pagination;
use Pagination\StrategyGoogle;

if (isset($_GET['page']) && is_numeric($_GET['page'])) {
    $page = $_GET['page'];
} else {
    $page = 1;
}

//use pagination class with results, per page and page
$pagination = new Pagination($countAll, $itemsPerPage, $page);
//get indexes in page
$indexes = $pagination->getIndexes(new StrategyGoogle(10));
$iterator = $indexes->getIterator();
//get all indexes
$all = $pagination->getAllIndexesOfPages();
$iteratorAll = $all->getIterator();

?>

<div class="row">
    <div class="col-md-12">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="?page=<?php echo $pagination->getFirstPage(); ?>" aria-label="First">
                        <span aria-hidden="true">First</span>
                    </a>
                </li>
                <li>
                    <a href="?page=<?php echo $pagination->getPreviousPage(); ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <?php while ($iterator->valid()): ?>
                    <li>
                        <a href="?page=<?php echo $iterator->current() ?>">
                            <?php echo $iterator->current() ?>
                        </a>
                    </li>
                    <?php $iterator->next(); endwhile; ?>
                <li>
                    <a href="?page=<?php echo $pagination->getNextPage(); ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li>
                    <a href="?page=<?php echo $pagination->getLastPage(); ?>" aria-label="Last">
                        <span aria-hidden="true">Last</span>
                    </a>
                </li>
            </ul>
        </nav>

    </div>

</div>