<?php

if (! isset($posts) || ! is_array($posts)) {
    echo 'No posts!';
}

?>

<?php
echo $view->renderWidget([
    'widget' => \Frontend\Widget\Breadcrumbs::class,
    'method' => 'getCategoryBreadcrumbs',
    'params' => [
    ],
]);
?>

<?php
echo $view->renderWidget([
    'widget' => \Frontend\Widget\ListingArticles::class,
    'method' => 'renderWidget',
    'params' => [
        'posts' => $posts
    ],
]);
?>

<?php
echo $view->renderWidget([
    'widget' => \Frontend\Widget\Pagination::class,
    'method' => 'renderWidget',
    'params' => [
        'posts' => $posts,
        'itemsPerPage' => $itemsPerPage,
        'countAll' => $countAll,
    ],
]);
?>
