<?php

if (! isset($subcategories) || ! is_array($subcategories)) {
    echo 'Categories missing!';
}
?>

<?php
echo $view->renderWidget([
    'widget' => \Frontend\Widget\Breadcrumbs::class,
    'method' => 'getCategoryBreadcrumbs',
    'params' => [
    ],
]);
?>


<ul class="list-group">
    <?php
    foreach ($subcategories as $category) {

        $url = \Core\Common\UrlHelper::getCategoryUrlTreeBySlug($category['slug']);

        ?>
        <li class="list-group-item"><a href="<?php echo $url; ?>"><?php echo $category['name'] ?></a></li>
        <?php
    }
    ?>
</ul>